plugins {
    id 'com.android.library'
    id 'com.vanniktech.maven.publish'
}

android {
    namespace 'moe.div.mobase'
    compileSdk 37

    defaultConfig {
        minSdk 29
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    api 'androidx.appcompat:appcompat:1.8.0'
    api 'com.google.android.material:material:1.14.0'
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(
            "moe.div",
            "mobase",
            "2.0.0"
    )

    pom {
        name = "MoBase"
        description = "A lightweight Android base library."
        inceptionYear = "2020"
        url = "https://github.com/H-Mo/MoBase"

        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "https://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }

        developers {
            developer {
                id = "H-Mo"
                name = "涂山墨墨"
                url = "https://github.com/H-Mo"
            }
        }

        scm {
            url = "https://github.com/H-Mo/MoBase"
            connection = "scm:git:git://github.com/H-Mo/MoBase.git"
            developerConnection = "scm:git:ssh://git@github.com/H-Mo/MoBase.git"
        }
    }
}